@baseUrl = http://localhost:3000

@name=create-new-recipe
POST {{baseUrl}}/recipe HTTP/1.1
Content-Type: application/json

{
    "title": "Beef Tacos"
}

###

@name=get-recipe
GET {{baseUrl}}/recipe/7

###
@name=GetRecipes
GET {{baseUrl}}/recipes

###
GET {{baseUrl}}/recipe/2/ingredients

###
GET {{baseUrl}}/ingredient/6

###
POST {{baseUrl}}/recipe/1/ingredient HTTP/1.1
Content-Type: application/json

{
    "name": "bell pepper",
    "quantity": 8,
    "unit": "oz"
}
###
#-----------------------------------
# INSTRUCTIONS

GET {{baseUrl}}/recipe/1/instructions
###

GET {{baseUrl}}/instruction/1

###
POST {{baseUrl}}/recipe/1/instruction HTTP/1.1
Content-Type: application/json

{
    "step": 2,
    "description": "Mix the ground beef with the seasonings"
}


# CTRL + SHIFT + o to navigate to the request